### ISSUE TITLE
Excepcion when instantiating module

### ISSUE THREAD

**Issue by jpardobl** [maros/Zway-AutoOffInactive#1]
Hello.

When I instantiate the module I get the following  stacktrace:

```
[2016-01-08 11:17:57.073] [I] [core] Notification: error (core): Cannot instantiate module: AutoOffInactive: TypeError: Cannot read property 'call' of undefined
[2016-01-08 11:17:57.107] [I] [core] TypeError: Cannot read property 'call' of undefined
at new AutoOffInactive (automation/modules/AutoOffInactive/index.js:14:27)
at AutomationController.instantiateModule (automation/classes/AutomationController.js:287:24)
at AutomationController.reconfigureInstance (automation/classes/AutomationController.js:576:22)
at ZAutomationAPIWebRequest._.extend.reconfigureInstanceFunc (automation/ZAutomationAPIProvider.js:706:40)
at ZAutomationAPIWebRequest.handlerFunc (automation/ZAutomationAPIProvider.js:1353:52)
at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
at automation/WebserverRequestRouter.js:32:35
at WebServer.document_root (automation/Webserver.js:27:11)
```

The version of the server 2.1.1.

Thanks in advance.

**Comment by maros** [comment]
This bug should already be fixed in the master branch. Will release this weekend

**Comment by jpardobl** [comment]
Thank you,

**Comment by jpardobl** [comment]
One question: I'm new to Zway. I want to develop and publish a module to control Honeywell Total Connect Comfort Thermostat from the Zway. Is there a way to test the module while its in development stage without the need of reloading the whole server with every change I made in the code??
Thanks in advance.

**Comment by maros** [comment]
Unfortunately every module reload requires a server restart for proper module initialisation.
